apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\repositories\github\challenges\docker\kompose.exe convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: db
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: db
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\repositories\github\challenges\docker\kompose.exe convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.network/wp-network: "true"
        io.kompose.service: db
    spec:
      containers:
      - args:
        - --default_authentication_plugin=mysql_native_password
        - --character-set-server=utf8mb4
        - --collation-server=utf8mb4_unicode_ci
        env:
        - name: DB_CONTAINER_PORT
          valueFrom:
            configMapKeyRef:
              key: DB_CONTAINER_PORT
              name: env
        - name: DB_HOST_IP
          valueFrom:
            configMapKeyRef:
              key: DB_HOST_IP
              name: env
        - name: DB_HOST_PORT
          valueFrom:
            configMapKeyRef:
              key: DB_HOST_PORT
              name: env
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              key: DB_NAME
              name: env
        - name: DB_ROOT_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: DB_ROOT_PASSWORD
              name: env
        - name: DB_ROOT_USER
          valueFrom:
            configMapKeyRef:
              key: DB_ROOT_USER
              name: env
        - name: HOST_IP
          valueFrom:
            configMapKeyRef:
              key: HOST_IP
              name: env
        - name: MYSQL_DATABASE
        - name: MYSQL_PASSWORD
        - name: MYSQL_ROOT_PASSWORD
        - name: MYSQL_USER
        - name: PMA_CONTAINER_PORT
          valueFrom:
            configMapKeyRef:
              key: PMA_CONTAINER_PORT
              name: env
        - name: PMA_HOST_PORT
          valueFrom:
            configMapKeyRef:
              key: PMA_HOST_PORT
              name: env
        - name: PMA_PORT
          valueFrom:
            configMapKeyRef:
              key: PMA_PORT
              name: env
        - name: WP_CONTAINER_PORT
          valueFrom:
            configMapKeyRef:
              key: WP_CONTAINER_PORT
              name: env
        - name: WP_DB_PASS
          valueFrom:
            configMapKeyRef:
              key: WP_DB_PASS
              name: env
        - name: WP_DB_USER
          valueFrom:
            configMapKeyRef:
              key: WP_DB_USER
              name: env
        - name: WP_HOST_PORT
          valueFrom:
            configMapKeyRef:
              key: WP_HOST_PORT
              name: env
        - name: WP_TABLE_PREFIX
          valueFrom:
            configMapKeyRef:
              key: WP_TABLE_PREFIX
              name: env
        image: mysql:5.7.34
        imagePullPolicy: ""
        name: mysql
        ports:
        - containerPort: 3306
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: db-data
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: db-data
        persistentVolumeClaim:
          claimName: db-data
status: {}
