apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  ports:
  - name: "WordPressPort"
    port: 8080
    targetPort: 80
  selector:
    app: wordpress
    tier: frontend
  type: LoadBalancer

